AllCops:
  TargetRubyVersion: 3.3.4
  NewCops: enable

Style:
  Documentation: true
  MethodDefParentheses:
    EnforcedStyle: require_parentheses
  StringLiterals:
    EnforcedStyle: double_quotes

Layout:
  LineLength:
    Max: 80

Metrics:
  MethodLength:
    Max: 10
  BlockLength:
    Max: 25
  ClassLength:
    Max: 100

Lint:
  AssignmentInCondition: true
  NonLocalExitFromIterator: true
  LiteralInInterpolation: true
  UnusedBlockArgument: true
  UnusedMethodArgument: true
  UselessAssignment: true

Security:
  Eval: true