AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style:
  MethodDefParentheses:
    EnforcedStyle: require_parentheses
  ReturnNil:
    Enabled: false

Metrics:
  MethodLength:
    Max: 10
  ClassLength:
    Max: 100
  CyclomaticComplexity:
    Max: 6

Layout:
  LineLength:
    Enabled: false
  IndentationStyle:
    EnforcedStyle: tabs